package com.santi.recetarium.entity;
// Generated 13 abr. 2021 11:28:27 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RecipeIngredientId generated by hbm2java
 */
@Embeddable
public class RecipeIngredientId implements java.io.Serializable {

	private long idRecipe;
	private long idIngredient;

	public RecipeIngredientId() {
	}

	public RecipeIngredientId(long idRecipe, long idIngredient) {
		this.idRecipe = idRecipe;
		this.idIngredient = idIngredient;
	}

	@Column(name = "id_recipe", nullable = false)
	public long getIdRecipe() {
		return this.idRecipe;
	}

	public void setIdRecipe(long idRecipe) {
		this.idRecipe = idRecipe;
	}

	@Column(name = "id_ingredient", nullable = false)
	public long getIdIngredient() {
		return this.idIngredient;
	}

	public void setIdIngredient(long idIngredient) {
		this.idIngredient = idIngredient;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecipeIngredientId))
			return false;
		RecipeIngredientId castOther = (RecipeIngredientId) other;

		return (this.getIdRecipe() == castOther.getIdRecipe())
				&& (this.getIdIngredient() == castOther.getIdIngredient());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdRecipe();
		result = 37 * result + (int) this.getIdIngredient();
		return result;
	}

}
